# Generated by Django 4.1 on 2022-10-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('phno', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('purpose', models.CharField(max_length=250)),
                ('material1', models.CharField(max_length=250)),
                ('material2', models.CharField(max_length=250)),
                ('material3', models.CharField(max_length=250)),
                ('material4', models.CharField(max_length=250)),
                ('material5', models.CharField(max_length=250)),
            ],
        ),
    ]
